import enum

class Category(enum.Enum):
    GENERAL =  "Uncategorized News"
    BUSINESS = "Business News"
    ENTERTAINMENT = "Entertainment News"
    HEALTH = "Health News"
    SCIENCE = "Science News"
    SPORTS = "Sport News"
    TECHNOLOGY = "Technology News"

class Country(enum.Enum):
    AR = "Argentina"
    AU = "Australia"
    AT = "Austria"
    BE = "Belgium"
    BR = "Brazil"
    BG = "Bulgaria"
    CA = "Canada"
    CN = "China"
    CO = "Columbia"
    CZ = "Czech Republic"
    EG = "Egypt"
    FR = "France"
    DE = "Germany"
    GR = "Greece"
    HK = "Hong Kong"
    HU = "Hungary"
    IN = "India"
    ID = "Indonesian"
    IE = "Ireland"
    IL = "Israel"
    IT = "Italy"
    JP = "Japan"
    LV = "Latvia"
    LT = "Lithuania"
    MY = "Malaysia"
    MX = "Mexico"
    MA = "Marocco"
    NL = "Netherlands"
    NZ = "New Zealand"
    NG = "Nigeria"
    NO = "Norway"
    PH = "Philippines"
    PL = "Poland"
    PT = "Portugal"
    RO = "Romania"
    SA = "Saudi Arabia"
    RS = "Serbia"
    SG = "Singapore"
    SK = "Slovakia"
    SI = "Slovenia"
    ZA = "South Africa"
    KR = "South Korea"
    SE = "Sweden"
    CH = "Switzerland"
    TW = "Taiwan"
    TH = "Thailand"
    TR = "Turkey"
    AE = "UAE"
    UA = "Ukraine"
    GB = "United Kingdom"
    US = "United States"
    VE = "Venezuela"

class Source(enum.Enum):
    CNN = "cnn"
    BBC = "bbc"

class Language(enum.Enum):
    AR = "Arabic"
    DE = "German"
    EN = "English"
    ES = "Spanish"
    FR = "French"
    HE = "Hebrew"
    IT = "Italian"
    NL = "Dutch"
    NO = "Norwegian"
    PT = "Portuguese"
    RU = "Russian"
    SE = 'Swedish'
    ZH = "Chinese"