import enum


class Category(enum.Enum):
    GENERAL = "general"
    BUSINESS = "business"
    ENTERTAINMENT = "entertainment"
    HEALTH = "health"
    SCIENCE = "science"
    SPORTS = "sports"
    TECHNOLOGY = "technology"


class Country(enum.Enum):
    AR = "ar"
    AU = "au"
    AT = "at"
    BE = "be"
    BR = "br"
    BG = "bg"
    CA = "ca"
    CN = "cn"
    CO = "co"
    CZ = "cz"
    EG = "eg"
    FR = "fr"
    DE = "de"
    GR = "gr"
    HK = "hk"
    HU = "hu"
    IN = "in"
    ID = "id"
    IE = "ie"
    IL = "il"
    IT = "it"
    JP = "jp"
    LV = "lv"
    LT = "lt"
    MY = "my"
    MX = "mx"
    MA = "ma"
    NL = "nl"
    NZ = "nz"
    NG = "ng"
    NO = "no"
    PH = "ph"
    PL = "pl"
    PT = "pt"
    RO = "ro"
    SA = "sa"
    RS = "rs"
    SG = "sg"
    SK = "sk"
    SI = "si"
    ZA = "za"
    KR = "kr"
    SE = "se"
    CH = "ch"
    TW = "tw"
    TH = "th"
    TR = "tr"
    AE = "ae"
    UA = "ua"
    GB = "gb"
    US = "us"
    VE = "ve"


class Source(enum.Enum):
    CNN = "cnn"
    BBC = "bbc"


class Language(enum.Enum):
    AR = "ar"
    DE = "de"
    EN = "en"
    ES = "es"
    FR = "fr"
    HE = "he"
    IT = "it"
    NL = "nl"
    NO = "no"
    PT = "pt"
    RU = "ru"
    SE = 'se'
    ZH = "zh"
