"""create user search settings table

Revision ID: 8846985103e3
Revises: 9671ac226f62
Create Date: 2022-03-18 10:10:23.184515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8846985103e3'
down_revision = '9671ac226f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Enum('AR', 'AU', 'AT', 'BE', 'BR', 'BG', 'CA', 'CN', 'CO', 'CZ', 'EG', 'FR', 'DE', 'GR', 'HK', 'HU', 'IN', 'ID', 'IE', 'IL', 'IT', 'JP', 'LV', 'LT', 'MY', 'MX', 'MA', 'NL', 'NZ', 'NG', 'NO', 'PH', 'PL', 'PT', 'RO', 'SA', 'RS', 'SG', 'SK', 'SI', 'ZA', 'KR', 'SE', 'CH', 'TW', 'TH', 'TR', 'AE', 'UA', 'GB', 'US', 'VE', name='country'), nullable=True),
    sa.Column('category', sa.Enum('GENERAL', 'BUSINESS', 'ENTERTAINMENT', 'HEALTH', 'SCIENCE', 'SPORTS', 'TECHNOLOGY', name='category'), nullable=True),
    sa.Column('source', sa.Enum('CNN', 'BBC', name='source'), nullable=True),
    sa.Column('language', sa.Enum('AR', 'DE', 'EN', 'ES', 'FR', 'HE', 'IT', 'NL', 'NO', 'PT', 'RU', 'SE', 'ZH', name='language'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_search_settings')
    # ### end Alembic commands ###
