"""set email to not be nullable

Revision ID: aa4ab5dc2372
Revises: b1c6c48942cd
Create Date: 2022-04-27 08:18:04.798155

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa4ab5dc2372"
down_revision = "b1c6c48942cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=25), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=25), nullable=True)
    # ### end Alembic commands ###
