"""add relationship between user and usersearchsettings

Revision ID: d1d321320cf7
Revises: 54b5d8c5424c
Create Date: 2022-03-23 12:02:58.492177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d321320cf7'
down_revision = '54b5d8c5424c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_search_settings', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_search_settings', type_='unique')
    # ### end Alembic commands ###
