name: mypy checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: pip install --upgrade pipenv
    - run: pipenv install mypy==v0.902
    - run: pipenv run mypy --strict $(git ls-files ‘*.py’)
